export { default as HeroSection } from "./Hero-Section";
export { default as Reputation } from "./Reputation"
export { default as AboutUs } from "./AboutUs"
export { default as Services } from "./Services"
export { default as Stats } from './Stats';
export { default as Ads } from "./Ads";
export { default as Projects } from "./Projects";
export { default as ContentUs } from "./ContentUs";
export { default as Bottom } from "./Bottom";
export { default as Footer } from "./Footer";